[package]
name = "mrkdwn2markdown"
version = "0.4.0"
edition = "2021"
description = "Converts mrkdwn blocks to markdown"

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
