[package]
name = "mrkdwn2markdown"
version = "0.2.0"
edition = "2021"
description = "Converts mrkdwn blocks to markdown"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
